## Primero cargamos los datos y librerias

In [1]:
import warnings
warnings.filterwarnings("ignore")

from pathlib import Path
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

DATA_DIR = Path("../datasets")
pd.set_option("display.max_columns", 50)

df = pd.read_csv(DATA_DIR / "iris.csv")
display(df.head())
df.info()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    str
dtypes: float64(4), str(1)
memory usage: 6.0 KB

## Limpieza basica y tipos de datos

In [19]:
df_clean = df.copy()

# Limpiar duplicados
print("Duplicados:", df_clean.duplicated().sum())
df_clean = df_clean.drop_duplicates()

# Rellenar nulos
print("\nNulos por columna:")
print(df_clean.isnull().sum())

num_cols = df_clean.select_dtypes(include="number").columns
df_clean[num_cols] = df_clean[num_cols].fillna(df_clean[num_cols].median())

df_clean["species"] = df_clean["species"].fillna("desconocido")

# Comprobación final de nulos
print("\nNulos después:")
print(df_clean.isnull().sum())

Duplicados: 3

Nulos por columna:
sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

Nulos después:
sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

## Resumen estadistico

In [15]:
desc = df_clean.describe(include="all")
desc = desc.apply(lambda col: col.round(2) if col.dtype != "object" else col)

display(desc)

        sepal_length  sepal_width  petal_length  petal_width     species
count         147.00       147.00        147.00       147.00         147
unique           NaN          NaN           NaN          NaN           3
top              NaN          NaN           NaN          NaN  versicolor
freq             NaN          NaN           NaN          NaN          50
mean            5.86         3.06          3.78         1.21         NaN
std             0.83         0.44          1.76         0.76         NaN
min             4.30         2.00          1.00         0.10         NaN
25%             5.10         2.80          1.60         0.30         NaN
50%             5.80         3.00          4.40         1.30         NaN
75%             6.40         3.30          5.10         1.80         NaN
max             7.90         4.40          6.90         2.50         NaN

## Distribucion de clases

In [14]:
print("\nDistribución de especies:")
print(df_clean["species"].value_counts())

print("\nDistribución relativa:")
print(df_clean["species"].value_counts(normalize=True).round(2))

Distribución de especies:
species
versicolor    50
virginica     49
setosa        48
Name: count, dtype: int64

Distribución relativa:
species
versicolor   0.34
virginica    0.33
setosa       0.33
Name: proportion, dtype: float64

## Estadisticas numericas y categoricas

In [20]:
num_desc = df_clean.describe().round(2)
cat_desc = df_clean.describe(include="object")

print("\nVARIABLES NUMERICAS:")
display(num_desc)

print("\nVARIABLES CATEGORICAS:")
display(cat_desc)

VARIABLES NUMERICAS:

       sepal_length  sepal_width  petal_length  petal_width
count        147.00       147.00        147.00       147.00
mean           5.86         3.06          3.78         1.21
std            0.83         0.44          1.76         0.76
min            4.30         2.00          1.00         0.10
25%            5.10         2.80          1.60         0.30
50%            5.80         3.00          4.40         1.30
75%            6.40         3.30          5.10         1.80
max            7.90         4.40          6.90         2.50

VARIABLES CATEGORICAS:

           species
count          147
unique           3
top     versicolor
freq            50